export const API_ENDPOINTS = {
  projects: "/api/projects",
  projectsWithStats: "/api/projects/with-stats",
  projectTypes: "/api/project-types",
  materials: "/api/materials",
  materialPurchases: "/api/material-purchases",
  suppliers: "/api/suppliers",
  supplierStatistics: "/api/suppliers/statistics",
  autocomplete: "/api/autocomplete",
  autocompleteAdmin: "/api/autocomplete-admin",
  notifications: "/api/notifications",
  workers: "/api/workers",
  workerTypes: "/api/worker-types",
  workerTransfers: "/api/worker-transfers",
  workerMiscExpenses: "/api/worker-misc-expenses",
  workerAttendance: "/api/worker-attendance",
  transportationExpenses: "/api/transportation-expenses",
  financialSummary: "/api/financial-summary",
  dailyExpenses: "/api/daily-expenses",
  dailyExpenseSummaries: "/api/daily-expense-summaries",
  projectFundTransfers: "/api/project-fund-transfers",
  fundTransfers: "/api/fund-transfers",
  tasks: "/api/tasks",
  wells: "/api/wells",
  equipment: "/api/equipment",
  equipmentMovements: "/api/equipment-movements",
  users: "/api/users",
  usersList: "/api/users/list",
  healthStats: "/api/health/stats",
  health: "/api/health",
  recentActivities: "/api/recent-activities",
  backups: "/api/backups",
  backupsStatus: "/api/backups/status",
  backupsLogs: "/api/backups/logs",
  backupsDatabases: "/api/backups/databases",
  aiSessions: "/api/ai/sessions",
  syncFullBackup: "/api/sync/full-backup",
  syncLatestBackup: "/api/sync/latest-backup",
  syncCompare: "/api/sync/compare",
  securityPolicies: "/api/security/policies",
  securityViolations: "/api/security/violations",
  securitySuggestions: "/api/security/suggestions",
  metrics: "/api/metrics/current",
  diagnostics: "/api/diagnostics/checks",
  reports: "/api/reports",
  syncAuditLogs: "/api/sync-audit/logs",
  syncAuditStats: "/api/sync-audit/stats",
  syncAuditModules: "/api/sync-audit/modules",

  auth: {
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    register: "/api/auth/register",
    verifyEmail: "/api/auth/verify-email",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    refreshToken: "/api/auth/refresh-token",
    me: "/api/auth/me",
  },

  projectById: (id: string) => `/api/projects/${id}`,
  workerById: (id: string) => `/api/workers/${id}`,
  notificationById: (id: string) => `/api/notifications/${id}`,
  notificationMarkRead: (id: string) => `/api/notifications/${id}/read`,
  notificationsMarkAllRead: "/api/notifications/mark-all-read",
  projectWorkers: (projectId: string) => `/api/projects/${projectId}/workers`,
  projectMaterialPurchases: (projectId: string, date?: string) =>
    date ? `/api/projects/${projectId}/material-purchases?date=${date}` : `/api/projects/${projectId}/material-purchases`,
  projectWorkerAttendance: (projectId: string, date?: string) =>
    date ? `/api/projects/${projectId}/worker-attendance?date=${date}` : `/api/projects/${projectId}/worker-attendance`,
  projectDailyExpenses: (projectId: string, date: string) =>
    `/api/projects/${projectId}/daily-expenses/${date}`,
  projectPreviousBalance: (projectId: string, date?: string) =>
    date ? `/api/projects/${projectId}/previous-balance/${date}` : `/api/projects/${projectId}/previous-balance`,
  projectDailySummary: (projectId: string, date: string) =>
    `/api/projects/${projectId}/daily-summary/${date}`,
  projectStats: (projectId: string) => `/api/projects/${projectId}/stats`,
} as const;
