ALTER TABLE "autocomplete_data" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "autocomplete_data" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "daily_expense_summaries" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "daily_expense_summaries" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "equipment_movements" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "equipment_movements" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "equipment_movements" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "equipment_movements" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "equipment_movements" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "fund_transfers" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "fund_transfers" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "journal_entries" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "journal_entries" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "material_categories" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "material_categories" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "material_purchases" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "material_purchases" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "permission_audit_logs" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "permission_audit_logs" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "permission_audit_logs" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "permission_audit_logs" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "security_policies" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "security_policies" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "security_policies" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "security_policies" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "security_policy_implementations" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "security_policy_implementations" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "security_policy_implementations" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "security_policy_implementations" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "security_policy_suggestions" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "security_policy_suggestions" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "security_policy_suggestions" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "security_policy_suggestions" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "security_policy_violations" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "security_policy_violations" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "security_policy_violations" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "security_policy_violations" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "supplier_payments" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "supplier_payments" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "transportation_expenses" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "transportation_expenses" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "user_project_permissions" ADD COLUMN IF NOT EXISTS "hlc_timestamp" TEXT;
ALTER TABLE "user_project_permissions" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "user_project_permissions" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "user_project_permissions" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_crew_workers" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_crew_workers" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "well_crew_workers" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_crew_workers" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_crew_workers" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_expenses" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_expenses" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_receptions" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_receptions" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "well_receptions" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_receptions" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_receptions" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_solar_components" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_solar_components" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "well_solar_components" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_solar_components" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_solar_components" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_tasks" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_tasks" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_transport_details" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_transport_details" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "well_transport_details" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_transport_details" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_transport_details" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "well_work_crews" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_work_crews" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "well_work_crews" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "well_work_crews" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "well_work_crews" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_attendance" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_attendance" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_balances" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_balances" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_misc_expenses" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_misc_expenses" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_settlement_lines" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "worker_settlement_lines" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "worker_settlement_lines" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "worker_settlement_lines" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_settlement_lines" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_settlements" ADD COLUMN IF NOT EXISTS "is_local" BOOLEAN DEFAULT FALSE;
ALTER TABLE "worker_settlements" ADD COLUMN IF NOT EXISTS "synced" BOOLEAN DEFAULT TRUE;
ALTER TABLE "worker_settlements" ADD COLUMN IF NOT EXISTS "pending_sync" BOOLEAN DEFAULT FALSE;
ALTER TABLE "worker_settlements" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_settlements" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_transfers" ADD COLUMN IF NOT EXISTS "created_by" VARCHAR;
ALTER TABLE "worker_transfers" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_transfers" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
ALTER TABLE "worker_types" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE "worker_types" ADD COLUMN IF NOT EXISTS "last_modified_by" VARCHAR;
