[build]
  # أمر البناء محدث لإدارة المشاريع الإنشائية
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  # متغيرات البيئة لنظام التتبع المتقدم
  ERROR_TRACKING_ENABLED = "true"
  ADVANCED_LOGGING = "true"
  ARABIC_ERROR_MESSAGES = "true"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override, X-Error-Tracking"
    Access-Control-Max-Age = "86400"
    # Headers خاصة لنظام التتبع المتقدم للأخطاء
    X-Error-Tracking = "enabled"
    X-System-Health = "monitored"
    X-Arabic-Support = "enabled"
    # تحسينات معالجة 502/504 errors
    X-502-Handler = "advanced"
    X-504-Handler = "optimized"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"